### ISSUE TITLE
Test different models

### ISSUE THREAD

**Issue by kindloaf** [dividiti/ck-caffe#104]
Hi,
When I first run "ck run ...", I got a list of models to choose from.
The next time I ran it, I don't see the list any more.
How can I choose a different model?

**Comment by psyhtest** [comment]
@kindloaf 
The first time you didn't have any models installed, so CK offered you to install one. You can view which one you selected as follows:
```
$ ck show env --tags=caffemodel
```
Now, because you have a single model installed, CK just selects it all the time. You need to install other models for CK to present you with a choice.

You can list all models available in the CK-Caffe repository as follows:
```
ck list ck-caffe:package:caffemodel* --print_full
ck-caffe:package:caffemodel-bvlc-alexnet-fast-mirror
ck-caffe:package:caffemodel-tidsp-jacintonet11-non-sparse
ck-caffe:package:caffemodel-deepscale-squeezenet-1.1
ck-caffe:package:caffemodel-bvlc-alexnet
ck-caffe:package:caffemodel-deepscale-squeezenet-1.0
ck-caffe:package:caffemodel-bvlc-googlenet
ck-caffe:package:caffemodel-resnet101
ck-caffe:package:caffemodel-resnet152
ck-caffe:package:caffemodel-bvlc-googlenet-fast-mirror
ck-caffe:package:caffemodel-vgg19
ck-caffe:package:caffemodel-resnet50
ck-caffe:package:caffemodel-vgg16
```
Then, just pick the line you fancy and append it to `ck install` e.g.
```
$ ck install ck-caffe:package:caffemodel-bvlc-googlenet-fast-mirror
```
Next time you run e.g. `ck run program:caffe` CK will offer you to select one of the installed models.
