### ISSUE TITLE
CK error: [program] can't find path to CK entry "module:program" (?:032630d041b4fd8a:?)!

### ISSUE THREAD

**Issue by chenyuqing** [dividiti/ck-caffe#142]
CK error: [program] can't find path to CK entry "module:program" (?:032630d041b4fd8a:?)!

**Comment by gfursin** [comment]
Hi! Can you please provide a command line? 

Usually this happens if you didn't pull CK repositories correctly and thus program module can't be found. 

Did you use this command to get this repo:
```
$ ck pull repo:ck-caffe
```

Can you please show the output of this command to see all CK repos:
```
$ ck ls repo
```

Also try to pull ck-caffe repo again and update all other repos:
```
$ ck pull repo:ck-caffe
$ ck pull all
```

Thanks!

**Comment by psyhtest** [comment]
Closing due to lack of response. Feel free to reopen.
