### ISSUE TITLE
There is no adb push command for package file deploy.prototxt before run command for android devices

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-caffe#16]
Adb push works fine for file "photo.jpg" from data set "image-jpeg-fgg" using meta like:

```
  "run_cmds": {
    "default": {
      "dataset_tags": [
        "image", 
        "jpeg", 
        "dataset"
      ], 

```

But looks like it does not work for packages like caffemodel-bvlc-alexnet using meta like: 

```
  "run_deps": {
    "caffemodel": {
      "force_target_as_host": "yes", 
      "local": "yes", 
      "name": "Caffe model (net and weights)", 
      "sort": 40, 
      "tags": "caffemodel"
    }
  }, 
```

it blocks issue #10 because now file deploy.prototxt should pushed manually to /data/local/tmp/tmp before commnand
`ck run program:caffe-time --target_os=android21-arm-v7a`

**Comment by gfursin** [comment]
It should be now fixed in the latest update. Please, make 'ck pull all' and check again. caffe-time and classification should have all their files sent to Android device automatically! 

By the way, note that model file is sent via meta
        "run_input_files": [
          "$<<CK_CAFFE_MODEL_FILE>>$"
        ],

CK picks it up from post-procest script and send file ...
Also, I now check if files has the same size (late should check time/date) on the remote device and your host and do not send the same files (needed not to send huge AlexNet weights file) ...

**Comment by DVEfremov** [comment]
works fine now 
so I'm closing it.
