### ISSUE TITLE
Make pakage dnn-proxy-caffe for integration with crowdsource-video-experiments-on-desktop

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-caffe#52]
Extract all lib-dependent code into separate package, which will be compiled into so-file (or dll) and will have well-known set of exported function - preparation model, parallel recognition etc. The app could find this proxy lib via CK, load and do real work through it. Such proxy-lib should be depend only on required things and hide any lib-specific stuff from the desktop app.

**Comment by psyhtest** [comment]
Please note that similar proxy libs will be required for [CK-TensorFlow](https://github.com/ctuning/ck-tensorflow), [CK-TensorRT](https://github.com/dividiti/ck-tensorrt), etc.

**Comment by gfursin** [comment]
We decided not to use this method for now but use caffe-classification binaries directly. However, we are not removing this method completely but archived it because it can be very useful for realistic applications. But for trying different libs (caffe-cpu,caffe-opencl,caffe-cuda), it requires lots of API gluing ... But thanks a lot for the first version - it was very useful! I close this ticket!
