### ISSUE TITLE
Prebuild Caffe distribution?

### ISSUE THREAD

**Issue by mrgloom** [dividiti/ck-caffe#93]
Are you planing to supply prebuild Caffe distribution?

For Linux it can be something like `sudo apt-get install <some-benchmark-package>`

For windows just `.zip` archive with statically linked `.exe`.

Also what about branch/commit of Caffe? is it fixed?
It will be great to test Caffe speed on some benchmark after each commit, as I understand they are using [Travis](https://travis-ci.org/BVLC/caffe), maybe benchmark can be integrated in it?

**Comment by dsavenko** [comment]
Hi! 

I don't know the plans, but it's just a huge work to supply a prebuild distrib, because it should be done for so many architectures and environments. But this would be nice to have it, for sure.

As for branches, there are a number of packages here for some branches/build setups like CPU, CUDA, OpenCL. Please, take a look here: https://github.com/dividiti/ck-caffe/tree/master/package . Directories named `lib-caffe-*` typically represent separate branches/build setups. 

Commits are not fixed. Unless specified otherwise, it takes the latest commit on the corresponding branch.

Yes, it can be integrated with Travis. Good idea!

**Comment by mrgloom** [comment]
As I understand it's some type of build configurations? What build system are you using?

**Comment by dsavenko** [comment]
`master` and `opencl` in directory names are branches. `cpu`, `cuda`, etc denote build flags (so, `master-cuda` means 'build the master branch with CUDA support'). 

Caffe provides CMake project for building, so we use CMake.

**Comment by gfursin** [comment]
We use Collective Knowledge build system which can build CK packages for Linux, Windows, MacOS and Android targets:
* https://github.com/ctuning/ck/wiki/Portable-workflows
* https://github.com/ctuning/ck-env

We use this build system because a) it has JSON API, b) it's natively integrated with our experiment workflow framework c) it lets multiple versions of the same software co-exist on the same system d) it allows you to select various versions during build (very important for us for performance evaluation of different libs and their versions) ...

CK build framework is just configurable wrappers for native build frameworks like make, cmake, etc. Caffe uses cmake, so we provide configurable wrapper with JSON API for Caffe's cmake ...

**Comment by psyhtest** [comment]
The CK package manager is actually a viable alternative to distributing prebuilt binaries (and many complications that come with that). On a fast machine, it takes less than 5 minutes from scratch to rebuild Caffe with all of its dependencies (e.g. compilers, compute libraries) resolved for this particular machine.

The performance of Caffe does not depend so much on its own code but on the libraries that it is built with. So you are more likely to observe an improvement or degradation due to changes in the library code (especially if it's taken from an actively developed project such as [Greantea libDNN](https://github.com/naibaf7/libdnn)). Moreover, such changes may only be relevant for a particular target e.g. the ARM Mali family of embedded GPUs. Which is why while a Travis build for a default CPU target would be useful, it would not solve the global problem of performance tracking.

Eventually, we would like to crowdsource performance tracking by aggregating results from the community and displaying them on a convenient dashboard. This would show, for example, which revisions of Caffe the community was able to build successfully on which target platforms and with which versions of its dependencies, and ideally also with some performance results of running benchmarks such as GoogleNet.

At this point, you might wonder what does "eventually" mean, i.e. when will this stuff be available? Well, we currently have limited capacity for this community work. (I could say we would try and do it in our spare time, but, frankly speaking, we are already doing a lot of community work in our spare time like [Artifact Evaluation](http://ctuning.org/ae/) at leading computer systems conferences!)

One way to increase our capacity would be to to find some sponsor for this activity so we could do it full-time. We basically know what to do, our CK technology is in good shape, so it would be a matter of several months to support crowdsourcing of performance tracking for Caffe.

The other way would be to rally up volunteers for this activity. Again, we have all the ingredients in place, and would gladly lead the effort to bake them into a tasty cake (or some other delicious meal if you don't like cakes).

So, @mrgloom, may we convince you to volunteer or become a sponsor? :)

**Comment by mrgloom** [comment]
I think I'm interested in participation.

You have some large scope and I'm only interested in these directions:
1.  PC GPU benchmark (preferably on Ubuntu 14.04) it can be adoptation of my small benchmark
No data needed for forward\backward pass time measuring only deploy.txt, and caffe already have this functionality via [caffe time](https://github.com/mrgloom/kaggle-dogs-vs-cats-solution/blob/master/forward_pass_time.sh), so maybe we can start from it without any dataset dependency, so table will be GPU type x Network type x Caffe build type (+environment?) x forward\backward pass time.
2.  (Maybe) Multi CPU Caffe build for training and prediction (for example Tensorflow have it out-of-the-box and with Caffe I have no luck).
3. (Maybe) Create some Windows build, because people with windows PC have lots of GPUs used for gaming, but running benchmark need to be really simple and user friendly like PCMark or something.

So I think we can start with 1st option, I'm not familiar with your `CK package manager`, so I need some clues how to start.
